BOT_NAME = "BinanceBot v1.1"

# 가상 계좌
STARTING_BALANCE = 1000000
POSITION_SIZE_PERCENT = 10
MAX_POSITIONS = 3

# 손절 / 익절
STOP_LOSS_PERCENT = 1.0
TAKE_PROFIT_PERCENT = 3.0

# 수수료
ROUND_TRIP_FEE_PERCENT = 0.10

# 일일 제한
DAILY_STOP_LOSS_PERCENT = 5.0
DAILY_TAKE_PROFIT_PERCENT = 10.0

# 스캔
TOP_VOLUME_SYMBOLS = 20
SCAN_INTERVAL_SECONDS = 60

# 모드
PAPER_TRADING = True